import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Image from "../components/Image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Data-start</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a
            href="https://ntnu.blackboard.com/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_70_1"
            className={`${styles.card} ${styles.bb}`}
          >
            <h2>Blackboard</h2>
            <p>
              Gå rett til blackboard og få oversikt over kunngjøringer i alle
              emner, slik som i gamle dager!
            </p>
          </a>

          <a
            href="https://innsida.ntnu.no/start#/feed/"
            className={`${styles.card} ${styles.innsida}`}
          >
            <h2>Innsida</h2>
            <p>
              Se kunngjøringer fra institutt / fakultet / NTNU, utlysning av
              assistentstillinger, og lignende.
            </p>
          </a>

          <a
            href="http://mail.ntnu.no/"
            className={`${styles.card} ${styles.mail}`}
          >
            <h2>NTNU epost</h2>
            <p>Logg inn på epost-kontoen din hos NTNU.</p>
          </a>

          <a
            href="https://use.mazemap.com/#v=1&config=ntnu&zlevel=1&center=10.404042,63.417890&zoom=14.6&campusid=1&utm_medium=longurl"
            className={`${styles.card} ${styles.mazemap}`}
          >
            <h2>MazeMap</h2>
            <p>Få oversikt over campus Gløshaugen og søk opp rom.</p>
          </a>

          <a
            href="https://tp.uio.no/ntnu/rombestilling/"
            className={styles.card}
          >
            <h2>Rombestilling</h2>
            <p>
              Bestill grupperom og lignende, og se timeplan for de forskjellige
              rommene på hele NTNU.
            </p>
          </a>

          <Link href="/work">
            <a className={styles.card}>
              <h2>Jobb for IT-studenter</h2>
              <p>
                Finn en oversikt over de mest populære offentlige
                jobbutlysningsportalene for IT-studenter på Gløshaugen.
              </p>
            </a>
          </Link>

          <a href="https://grades.no" className={styles.card}>
            <h2>Grades.no</h2>
            <p>Se karakterstatistikk på emner.</p>
          </a>

          <a href="https://emnr.no" className={`${styles.card} ${styles.emnr}`}>
            <h2>
              EMN<span style={{ color: "rgb(230, 57, 70)" }}>R</span>
            </h2>
            <p>Se verifiserte vurderinger av emner fra medstudenter.</p>
          </a>

          <a href="https://www.wikipendium.no" className={styles.card}>
            <h2>Wikipendium</h2>
            <p>
              Gratis nettbaserte kompendium skrevet av medstudenter i
              wikiformat.
            </p>
          </a>

          <a
            href="https://dvikan.no/gamle-ntnu-eksamener/"
            className={styles.card}
          >
            <h2>Dvikan gamle eksamener</h2>
            <p>Finn eldre eksamener på dvikan.no</p>
          </a>

          <a
            href="https://fsweb.no/studentweb/login.jsf?inst=FSNTNU"
            className={styles.card}
          >
            <h2>Studentweb</h2>
            <p>Meld deg opp i emner, sjekk eksamensdatoer og se vurderinger</p>
          </a>

          <a
            href="https://app.vitnemalsportalen.no/vp/login"
            className={`${styles.card} ${styles.vitnemal}`}
          >
            <h2>Vitnemålsportalen</h2>
            <p>
              Hent signert karakterutskrift, med mulighet for å dele via epost
              til (potensiell) arbeidsgiver
            </p>
          </a>

          <a
            href="https://abakus.no"
            className={`${styles.card} ${styles.abakus}`}
          >
            <h2>
              <span className={styles.image}>
                <Image
                  src={"./abakus.png"}
                  alt="Abakus Logo"
                  height={25}
                  width={110}
                />{" "}
              </span>
            </h2>
            <p>Nettsiden til linjeforeningen Abakus.</p>
          </a>

          <a
            href="https://online.ntnu.no"
            className={`${styles.card} ${styles.online}`}
          >
            <h2>
              <span className={styles.image}>
                <Image
                  src={"./online.svg"}
                  alt="Online Logo"
                  height={25}
                  width={100}
                />{" "}
              </span>
            </h2>
            <p>Nettsiden til linjeforeningen Online.</p>
          </a>

          <a
            href="https://tihlde.org"
            className={`${styles.card} ${styles.tihlde}`}
          >
            <h2>
              <span className={styles.image}>
                <Image
                  src={"./tihlde.png"}
                  alt="Tihlde Logo"
                  height={25}
                  width={140}
                />{" "}
              </span>
            </h2>
            <p>Nettsiden til linjeforeningen Tihlde.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Magssch/data-start"
          target="_blank"
          rel="noopener noreferrer"
        >
          Foreslå endringer på{" "}
          <span className={styles.logo}>
            <Image
              src={"./github.svg"}
              alt="Github Logo"
              width={16}
              height={16}
            />{" "}
          </span>
        </a>
      </footer>
    </div>
  );
}
